"""baseline schema

Revision ID: b8828ce648a2
Revises: 
Create Date: 2026-06-19 21:40:09.485614

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8828ce648a2'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema changes for this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holding_comparisons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comparison_date', sa.Date(), nullable=False),
    sa.Column('pp_group', sa.String(length=100), nullable=False),
    sa.Column('pp_account', sa.String(length=100), nullable=False),
    sa.Column('security_name', sa.String(length=255), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('pp_quantity', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('pp_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('pp_currency', sa.String(length=3), nullable=True),
    sa.Column('kubera_quantity', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('kubera_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('kubera_currency', sa.String(length=3), nullable=True),
    sa.Column('quantity_variance', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('quantity_variance_percent', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('value_variance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('value_variance_percent', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('is_matched', sa.Boolean(), nullable=False),
    sa.Column('is_pp_only', sa.Boolean(), nullable=False),
    sa.Column('is_kubera_only', sa.Boolean(), nullable=False),
    sa.Column('variance_threshold_exceeded', sa.Boolean(), nullable=False),
    sa.Column('quantity_tolerance_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('value_tolerance_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('investigation_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holding_comparisons_comparison_date'), 'holding_comparisons', ['comparison_date'], unique=False)
    op.create_index(op.f('ix_holding_comparisons_is_kubera_only'), 'holding_comparisons', ['is_kubera_only'], unique=False)
    op.create_index(op.f('ix_holding_comparisons_is_matched'), 'holding_comparisons', ['is_matched'], unique=False)
    op.create_index(op.f('ix_holding_comparisons_is_pp_only'), 'holding_comparisons', ['is_pp_only'], unique=False)
    op.create_index(op.f('ix_holding_comparisons_isin'), 'holding_comparisons', ['isin'], unique=False)
    op.create_index(op.f('ix_holding_comparisons_pp_account'), 'holding_comparisons', ['pp_account'], unique=False)
    op.create_index(op.f('ix_holding_comparisons_pp_group'), 'holding_comparisons', ['pp_group'], unique=False)
    op.create_index(op.f('ix_holding_comparisons_ticker'), 'holding_comparisons', ['ticker'], unique=False)
    op.create_index(op.f('ix_holding_comparisons_variance_threshold_exceeded'), 'holding_comparisons', ['variance_threshold_exceeded'], unique=False)
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=50), nullable=False),
    sa.Column('institution', sa.String(length=50), nullable=False),
    sa.Column('import_type', sa.String(length=50), nullable=False),
    sa.Column('source_file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('records_imported', sa.Integer(), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('records_errors', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('import_config', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id')
    )
    op.create_index(op.f('ix_import_batches_institution'), 'import_batches', ['institution'], unique=False)
    op.create_index(op.f('ix_import_batches_status'), 'import_batches', ['status'], unique=False)
    op.create_table('kubera_sheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sheet_id', sa.String(length=50), nullable=False),
    sa.Column('sheet_name', sa.String(length=100), nullable=False),
    sa.Column('pp_group_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sheet_id')
    )
    op.create_index(op.f('ix_kubera_sheets_pp_group_name'), 'kubera_sheets', ['pp_group_name'], unique=False)
    op.create_index(op.f('ix_kubera_sheets_sheet_name'), 'kubera_sheets', ['sheet_name'], unique=False)
    op.create_table('pp_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('is_retired', sa.Boolean(), nullable=False),
    sa.Column('attributes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('pp_bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('pattern', sa.String(length=500), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pp_client_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('config_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pp_import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=50), nullable=False),
    sa.Column('source_file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('pp_version', sa.Integer(), nullable=False),
    sa.Column('securities_imported', sa.Integer(), nullable=False),
    sa.Column('accounts_imported', sa.Integer(), nullable=False),
    sa.Column('portfolios_imported', sa.Integer(), nullable=False),
    sa.Column('transactions_imported', sa.Integer(), nullable=False),
    sa.Column('prices_imported', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id')
    )
    op.create_index(op.f('ix_pp_import_batches_status'), 'pp_import_batches', ['status'], unique=False)
    op.create_table('pp_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setting_category', sa.String(length=50), nullable=False),
    sa.Column('setting_key', sa.String(length=100), nullable=False),
    sa.Column('setting_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('setting_category', 'setting_key', name='uq_setting_category_key')
    )
    op.create_table('pp_transaction_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('unit_type', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('securities_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('wkn', sa.String(length=20), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('latest_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('delta_percent', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('delta_amount', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('latest_date', sa.Date(), nullable=True),
    sa.Column('last_historical_date', sa.Date(), nullable=True),
    sa.Column('first_historical_date', sa.Date(), nullable=True),
    sa.Column('quote_feed_historic', sa.String(length=100), nullable=True),
    sa.Column('quote_feed_latest', sa.String(length=100), nullable=True),
    sa.Column('url_historic_quotes', sa.String(length=500), nullable=True),
    sa.Column('url_latest_quotes', sa.String(length=500), nullable=True),
    sa.Column('next_ex_date', sa.Date(), nullable=True),
    sa.Column('next_payment_date', sa.Date(), nullable=True),
    sa.Column('next_payment_amount', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('logo', sa.String(length=500), nullable=True),
    sa.Column('ter', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('aum', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vendor', sa.String(length=100), nullable=True),
    sa.Column('acquisition_fee', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('management_fee', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('asset_classes_level1', sa.String(length=100), nullable=True),
    sa.Column('asset_classes', sa.String(length=200), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry_group', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('industries_gics_level4', sa.String(length=200), nullable=True),
    sa.Column('industries_gics', sa.String(length=200), nullable=True),
    sa.Column('industries_gics_sectors_level1', sa.String(length=100), nullable=True),
    sa.Column('industries_gics_sectors', sa.String(length=200), nullable=True),
    sa.Column('asset_allocation_level1', sa.String(length=100), nullable=True),
    sa.Column('asset_allocation_level2', sa.String(length=100), nullable=True),
    sa.Column('asset_allocation', sa.String(length=200), nullable=True),
    sa.Column('market', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('regions_msci_level3', sa.String(length=100), nullable=True),
    sa.Column('regions_msci', sa.String(length=200), nullable=True),
    sa.Column('type_of_security_level1', sa.String(length=100), nullable=True),
    sa.Column('type_of_security', sa.String(length=200), nullable=True),
    sa.Column('brx_plus_level1', sa.String(length=100), nullable=True),
    sa.Column('brx_plus_level2', sa.String(length=100), nullable=True),
    sa.Column('brx_plus', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('data_source', sa.String(length=50), nullable=False),
    sa.Column('data_quality_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_securities_master_isin'), 'securities_master', ['isin'], unique=True)
    op.create_index(op.f('ix_securities_master_name'), 'securities_master', ['name'], unique=False)
    op.create_index(op.f('ix_securities_master_sector'), 'securities_master', ['sector'], unique=False)
    op.create_index(op.f('ix_securities_master_symbol'), 'securities_master', ['symbol'], unique=False)
    op.create_index(op.f('ix_securities_master_type_of_security_level1'), 'securities_master', ['type_of_security_level1'], unique=False)
    op.create_index(op.f('ix_securities_master_wkn'), 'securities_master', ['wkn'], unique=False)
    op.create_table('transactions_altoira',
    sa.Column('statement_date', sa.Date(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('parsed_confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('requires_manual_review', sa.Boolean(), nullable=False),
    sa.Column('manually_reviewed', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('review_date', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('pdf_text_raw', sa.Text(), nullable=True),
    sa.Column('ocr_engine', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('settlement_date', sa.Date(), nullable=True),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('security_name', sa.String(length=255), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('cusip', sa.String(length=9), nullable=True),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('commission', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fees', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('account_name', sa.String(length=100), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('import_batch_id', sa.String(length=50), nullable=False),
    sa.Column('import_date', sa.DateTime(), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('source_line_number', sa.Integer(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('has_errors', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_altoira_account_name'), 'transactions_altoira', ['account_name'], unique=False)
    op.create_index(op.f('ix_transactions_altoira_account_number'), 'transactions_altoira', ['account_number'], unique=False)
    op.create_index(op.f('ix_transactions_altoira_cusip'), 'transactions_altoira', ['cusip'], unique=False)
    op.create_index(op.f('ix_transactions_altoira_has_errors'), 'transactions_altoira', ['has_errors'], unique=False)
    op.create_index(op.f('ix_transactions_altoira_import_batch_id'), 'transactions_altoira', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_transactions_altoira_is_processed'), 'transactions_altoira', ['is_processed'], unique=False)
    op.create_index(op.f('ix_transactions_altoira_isin'), 'transactions_altoira', ['isin'], unique=False)
    op.create_index(op.f('ix_transactions_altoira_manually_reviewed'), 'transactions_altoira', ['manually_reviewed'], unique=False)
    op.create_index(op.f('ix_transactions_altoira_requires_manual_review'), 'transactions_altoira', ['requires_manual_review'], unique=False)
    op.create_index(op.f('ix_transactions_altoira_settlement_date'), 'transactions_altoira', ['settlement_date'], unique=False)
    op.create_index(op.f('ix_transactions_altoira_symbol'), 'transactions_altoira', ['symbol'], unique=False)
    op.create_index(op.f('ix_transactions_altoira_transaction_date'), 'transactions_altoira', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_transactions_altoira_transaction_id'), 'transactions_altoira', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_transactions_altoira_transaction_type'), 'transactions_altoira', ['transaction_type'], unique=False)
    op.create_table('transactions_interactive_brokers',
    sa.Column('trade_id', sa.String(length=50), nullable=True),
    sa.Column('order_id', sa.String(length=50), nullable=True),
    sa.Column('execution_id', sa.String(length=50), nullable=True),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('multiplier', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('asset_class', sa.String(length=20), nullable=True),
    sa.Column('sec_type', sa.String(length=20), nullable=True),
    sa.Column('strike', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('expiry', sa.Date(), nullable=True),
    sa.Column('put_call', sa.String(length=1), nullable=True),
    sa.Column('underlying_symbol', sa.String(length=20), nullable=True),
    sa.Column('ib_commission', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('regulatory_fees', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('exchange_fees', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('settlement_date', sa.Date(), nullable=True),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('security_name', sa.String(length=255), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('cusip', sa.String(length=9), nullable=True),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('commission', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fees', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('account_name', sa.String(length=100), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('import_batch_id', sa.String(length=50), nullable=False),
    sa.Column('import_date', sa.DateTime(), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('source_line_number', sa.Integer(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('has_errors', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_id')
    )
    op.create_index(op.f('ix_transactions_interactive_brokers_account_name'), 'transactions_interactive_brokers', ['account_name'], unique=False)
    op.create_index(op.f('ix_transactions_interactive_brokers_account_number'), 'transactions_interactive_brokers', ['account_number'], unique=False)
    op.create_index(op.f('ix_transactions_interactive_brokers_cusip'), 'transactions_interactive_brokers', ['cusip'], unique=False)
    op.create_index(op.f('ix_transactions_interactive_brokers_has_errors'), 'transactions_interactive_brokers', ['has_errors'], unique=False)
    op.create_index(op.f('ix_transactions_interactive_brokers_import_batch_id'), 'transactions_interactive_brokers', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_transactions_interactive_brokers_is_processed'), 'transactions_interactive_brokers', ['is_processed'], unique=False)
    op.create_index(op.f('ix_transactions_interactive_brokers_isin'), 'transactions_interactive_brokers', ['isin'], unique=False)
    op.create_index(op.f('ix_transactions_interactive_brokers_settlement_date'), 'transactions_interactive_brokers', ['settlement_date'], unique=False)
    op.create_index(op.f('ix_transactions_interactive_brokers_symbol'), 'transactions_interactive_brokers', ['symbol'], unique=False)
    op.create_index(op.f('ix_transactions_interactive_brokers_transaction_date'), 'transactions_interactive_brokers', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_transactions_interactive_brokers_transaction_id'), 'transactions_interactive_brokers', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_transactions_interactive_brokers_transaction_type'), 'transactions_interactive_brokers', ['transaction_type'], unique=False)
    op.create_table('transactions_kubera',
    sa.Column('kubera_asset_id', sa.String(length=100), nullable=False),
    sa.Column('kubera_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('sheet_name', sa.String(length=100), nullable=False),
    sa.Column('section_name', sa.String(length=100), nullable=False),
    sa.Column('aggregator', sa.String(length=50), nullable=True),
    sa.Column('provider_name', sa.String(length=100), nullable=True),
    sa.Column('provider_account_id', sa.String(length=50), nullable=True),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.Column('is_validation_source', sa.Boolean(), nullable=False),
    sa.Column('matched_to_institution', sa.Boolean(), nullable=False),
    sa.Column('variance_flag', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('settlement_date', sa.Date(), nullable=True),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('security_name', sa.String(length=255), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('cusip', sa.String(length=9), nullable=True),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('commission', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fees', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('account_name', sa.String(length=100), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('import_batch_id', sa.String(length=50), nullable=False),
    sa.Column('import_date', sa.DateTime(), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('source_line_number', sa.Integer(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('has_errors', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kubera_transaction_id')
    )
    op.create_index(op.f('ix_transactions_kubera_account_name'), 'transactions_kubera', ['account_name'], unique=False)
    op.create_index(op.f('ix_transactions_kubera_account_number'), 'transactions_kubera', ['account_number'], unique=False)
    op.create_index(op.f('ix_transactions_kubera_cusip'), 'transactions_kubera', ['cusip'], unique=False)
    op.create_index(op.f('ix_transactions_kubera_has_errors'), 'transactions_kubera', ['has_errors'], unique=False)
    op.create_index(op.f('ix_transactions_kubera_import_batch_id'), 'transactions_kubera', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_transactions_kubera_is_processed'), 'transactions_kubera', ['is_processed'], unique=False)
    op.create_index(op.f('ix_transactions_kubera_is_validation_source'), 'transactions_kubera', ['is_validation_source'], unique=False)
    op.create_index(op.f('ix_transactions_kubera_isin'), 'transactions_kubera', ['isin'], unique=False)
    op.create_index(op.f('ix_transactions_kubera_kubera_asset_id'), 'transactions_kubera', ['kubera_asset_id'], unique=False)
    op.create_index(op.f('ix_transactions_kubera_matched_to_institution'), 'transactions_kubera', ['matched_to_institution'], unique=False)
    op.create_index(op.f('ix_transactions_kubera_section_name'), 'transactions_kubera', ['section_name'], unique=False)
    op.create_index(op.f('ix_transactions_kubera_settlement_date'), 'transactions_kubera', ['settlement_date'], unique=False)
    op.create_index(op.f('ix_transactions_kubera_sheet_name'), 'transactions_kubera', ['sheet_name'], unique=False)
    op.create_index(op.f('ix_transactions_kubera_symbol'), 'transactions_kubera', ['symbol'], unique=False)
    op.create_index(op.f('ix_transactions_kubera_transaction_date'), 'transactions_kubera', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_transactions_kubera_transaction_id'), 'transactions_kubera', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_transactions_kubera_transaction_type'), 'transactions_kubera', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_transactions_kubera_variance_flag'), 'transactions_kubera', ['variance_flag'], unique=False)
    op.create_table('transactions_wells_fargo',
    sa.Column('investment_objective', sa.String(length=100), nullable=True),
    sa.Column('account_type', sa.String(length=50), nullable=True),
    sa.Column('sub_account', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('investment_type', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('settlement_date', sa.Date(), nullable=True),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('security_name', sa.String(length=255), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('cusip', sa.String(length=9), nullable=True),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('commission', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fees', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('account_name', sa.String(length=100), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('import_batch_id', sa.String(length=50), nullable=False),
    sa.Column('import_date', sa.DateTime(), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('source_line_number', sa.Integer(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('has_errors', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_wells_fargo_account_name'), 'transactions_wells_fargo', ['account_name'], unique=False)
    op.create_index(op.f('ix_transactions_wells_fargo_account_number'), 'transactions_wells_fargo', ['account_number'], unique=False)
    op.create_index(op.f('ix_transactions_wells_fargo_cusip'), 'transactions_wells_fargo', ['cusip'], unique=False)
    op.create_index(op.f('ix_transactions_wells_fargo_has_errors'), 'transactions_wells_fargo', ['has_errors'], unique=False)
    op.create_index(op.f('ix_transactions_wells_fargo_import_batch_id'), 'transactions_wells_fargo', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_transactions_wells_fargo_is_processed'), 'transactions_wells_fargo', ['is_processed'], unique=False)
    op.create_index(op.f('ix_transactions_wells_fargo_isin'), 'transactions_wells_fargo', ['isin'], unique=False)
    op.create_index(op.f('ix_transactions_wells_fargo_settlement_date'), 'transactions_wells_fargo', ['settlement_date'], unique=False)
    op.create_index(op.f('ix_transactions_wells_fargo_symbol'), 'transactions_wells_fargo', ['symbol'], unique=False)
    op.create_index(op.f('ix_transactions_wells_fargo_transaction_date'), 'transactions_wells_fargo', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_transactions_wells_fargo_transaction_id'), 'transactions_wells_fargo', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_transactions_wells_fargo_transaction_type'), 'transactions_wells_fargo', ['transaction_type'], unique=False)
    op.create_table('kubera_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.String(length=50), nullable=False),
    sa.Column('section_name', sa.String(length=100), nullable=False),
    sa.Column('sheet_id', sa.Integer(), nullable=False),
    sa.Column('pp_account_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sheet_id'], ['kubera_sheets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id')
    )
    op.create_index(op.f('ix_kubera_sections_pp_account_name'), 'kubera_sections', ['pp_account_name'], unique=False)
    op.create_index(op.f('ix_kubera_sections_section_name'), 'kubera_sections', ['section_name'], unique=False)
    op.create_table('pp_account_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('cross_entry_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['pp_accounts.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities_master.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_pp_account_transactions_transaction_date'), 'pp_account_transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_pp_account_transactions_transaction_type'), 'pp_account_transactions', ['transaction_type'], unique=False)
    op.create_table('pp_portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_retired', sa.Boolean(), nullable=False),
    sa.Column('reference_account_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reference_account_id'], ['pp_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('pp_security_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('price_value', sa.BigInteger(), nullable=False),
    sa.Column('price_source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities_master.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('security_id', 'price_date', name='uq_security_price_date')
    )
    op.create_index(op.f('ix_pp_security_prices_price_date'), 'pp_security_prices', ['price_date'], unique=False)
    op.create_table('transactions_consolidated',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_institution', sa.String(length=50), nullable=False),
    sa.Column('source_transaction_id', sa.Integer(), nullable=False),
    sa.Column('source_table', sa.String(length=50), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('settlement_date', sa.Date(), nullable=True),
    sa.Column('security_master_id', sa.Integer(), nullable=True),
    sa.Column('security_name', sa.String(length=255), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('pp_group', sa.String(length=100), nullable=False),
    sa.Column('pp_account', sa.String(length=100), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('fees_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('quality_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('has_validation_issues', sa.Boolean(), nullable=False),
    sa.Column('validation_notes', sa.Text(), nullable=True),
    sa.Column('exported_to_pp', sa.Boolean(), nullable=False),
    sa.Column('export_batch_id', sa.String(length=50), nullable=True),
    sa.Column('export_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['security_master_id'], ['securities_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_consolidated_export_batch_id'), 'transactions_consolidated', ['export_batch_id'], unique=False)
    op.create_index(op.f('ix_transactions_consolidated_exported_to_pp'), 'transactions_consolidated', ['exported_to_pp'], unique=False)
    op.create_index(op.f('ix_transactions_consolidated_has_validation_issues'), 'transactions_consolidated', ['has_validation_issues'], unique=False)
    op.create_index(op.f('ix_transactions_consolidated_isin'), 'transactions_consolidated', ['isin'], unique=False)
    op.create_index(op.f('ix_transactions_consolidated_pp_account'), 'transactions_consolidated', ['pp_account'], unique=False)
    op.create_index(op.f('ix_transactions_consolidated_pp_group'), 'transactions_consolidated', ['pp_group'], unique=False)
    op.create_index(op.f('ix_transactions_consolidated_source_institution'), 'transactions_consolidated', ['source_institution'], unique=False)
    op.create_index(op.f('ix_transactions_consolidated_symbol'), 'transactions_consolidated', ['symbol'], unique=False)
    op.create_index(op.f('ix_transactions_consolidated_transaction_date'), 'transactions_consolidated', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_transactions_consolidated_transaction_type'), 'transactions_consolidated', ['transaction_type'], unique=False)
    op.create_table('kubera_holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kubera_asset_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('ticker_id', sa.Integer(), nullable=True),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('sub_type', sa.String(length=50), nullable=False),
    sa.Column('ticker_sub_type', sa.String(length=20), nullable=True),
    sa.Column('asset_class', sa.String(length=50), nullable=False),
    sa.Column('security_type', sa.String(length=50), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('ticker_sector', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('current_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('cost_per_share', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('cost_basis_total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cost_basis_for_tax', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('irr', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('unrealized_gain_loss', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('tax_on_unrealized_gain', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('holding_period_days', sa.Integer(), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tax_status', sa.String(length=20), nullable=True),
    sa.Column('geography_country', sa.String(length=50), nullable=True),
    sa.Column('geography_region', sa.String(length=50), nullable=True),
    sa.Column('liquidity', sa.String(length=20), nullable=True),
    sa.Column('investable', sa.String(length=50), nullable=True),
    sa.Column('ownership', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('aggregator', sa.String(length=50), nullable=True),
    sa.Column('provider_name', sa.String(length=100), nullable=True),
    sa.Column('provider_account_id', sa.String(length=50), nullable=True),
    sa.Column('provider_connection_id', sa.String(length=50), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('holdings_count', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.String(length=100), nullable=True),
    sa.Column('parent_name', sa.String(length=255), nullable=True),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('data_source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['kubera_sections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kubera_asset_id')
    )
    op.create_index(op.f('ix_kubera_holdings_asset_class'), 'kubera_holdings', ['asset_class'], unique=False)
    op.create_index(op.f('ix_kubera_holdings_isin'), 'kubera_holdings', ['isin'], unique=False)
    op.create_index(op.f('ix_kubera_holdings_name'), 'kubera_holdings', ['name'], unique=False)
    op.create_index(op.f('ix_kubera_holdings_sector'), 'kubera_holdings', ['sector'], unique=False)
    op.create_index(op.f('ix_kubera_holdings_snapshot_date'), 'kubera_holdings', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_kubera_holdings_sub_type'), 'kubera_holdings', ['sub_type'], unique=False)
    op.create_index(op.f('ix_kubera_holdings_ticker'), 'kubera_holdings', ['ticker'], unique=False)
    op.create_table('pp_portfolio_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('linked_account_transaction_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['linked_account_transaction_id'], ['pp_account_transactions.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['pp_portfolios.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities_master.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_pp_portfolio_transactions_transaction_date'), 'pp_portfolio_transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_pp_portfolio_transactions_transaction_type'), 'pp_portfolio_transactions', ['transaction_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the schema changes for this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pp_portfolio_transactions_transaction_type'), table_name='pp_portfolio_transactions')
    op.drop_index(op.f('ix_pp_portfolio_transactions_transaction_date'), table_name='pp_portfolio_transactions')
    op.drop_table('pp_portfolio_transactions')
    op.drop_index(op.f('ix_kubera_holdings_ticker'), table_name='kubera_holdings')
    op.drop_index(op.f('ix_kubera_holdings_sub_type'), table_name='kubera_holdings')
    op.drop_index(op.f('ix_kubera_holdings_snapshot_date'), table_name='kubera_holdings')
    op.drop_index(op.f('ix_kubera_holdings_sector'), table_name='kubera_holdings')
    op.drop_index(op.f('ix_kubera_holdings_name'), table_name='kubera_holdings')
    op.drop_index(op.f('ix_kubera_holdings_isin'), table_name='kubera_holdings')
    op.drop_index(op.f('ix_kubera_holdings_asset_class'), table_name='kubera_holdings')
    op.drop_table('kubera_holdings')
    op.drop_index(op.f('ix_transactions_consolidated_transaction_type'), table_name='transactions_consolidated')
    op.drop_index(op.f('ix_transactions_consolidated_transaction_date'), table_name='transactions_consolidated')
    op.drop_index(op.f('ix_transactions_consolidated_symbol'), table_name='transactions_consolidated')
    op.drop_index(op.f('ix_transactions_consolidated_source_institution'), table_name='transactions_consolidated')
    op.drop_index(op.f('ix_transactions_consolidated_pp_group'), table_name='transactions_consolidated')
    op.drop_index(op.f('ix_transactions_consolidated_pp_account'), table_name='transactions_consolidated')
    op.drop_index(op.f('ix_transactions_consolidated_isin'), table_name='transactions_consolidated')
    op.drop_index(op.f('ix_transactions_consolidated_has_validation_issues'), table_name='transactions_consolidated')
    op.drop_index(op.f('ix_transactions_consolidated_exported_to_pp'), table_name='transactions_consolidated')
    op.drop_index(op.f('ix_transactions_consolidated_export_batch_id'), table_name='transactions_consolidated')
    op.drop_table('transactions_consolidated')
    op.drop_index(op.f('ix_pp_security_prices_price_date'), table_name='pp_security_prices')
    op.drop_table('pp_security_prices')
    op.drop_table('pp_portfolios')
    op.drop_index(op.f('ix_pp_account_transactions_transaction_type'), table_name='pp_account_transactions')
    op.drop_index(op.f('ix_pp_account_transactions_transaction_date'), table_name='pp_account_transactions')
    op.drop_table('pp_account_transactions')
    op.drop_index(op.f('ix_kubera_sections_section_name'), table_name='kubera_sections')
    op.drop_index(op.f('ix_kubera_sections_pp_account_name'), table_name='kubera_sections')
    op.drop_table('kubera_sections')
    op.drop_index(op.f('ix_transactions_wells_fargo_transaction_type'), table_name='transactions_wells_fargo')
    op.drop_index(op.f('ix_transactions_wells_fargo_transaction_id'), table_name='transactions_wells_fargo')
    op.drop_index(op.f('ix_transactions_wells_fargo_transaction_date'), table_name='transactions_wells_fargo')
    op.drop_index(op.f('ix_transactions_wells_fargo_symbol'), table_name='transactions_wells_fargo')
    op.drop_index(op.f('ix_transactions_wells_fargo_settlement_date'), table_name='transactions_wells_fargo')
    op.drop_index(op.f('ix_transactions_wells_fargo_isin'), table_name='transactions_wells_fargo')
    op.drop_index(op.f('ix_transactions_wells_fargo_is_processed'), table_name='transactions_wells_fargo')
    op.drop_index(op.f('ix_transactions_wells_fargo_import_batch_id'), table_name='transactions_wells_fargo')
    op.drop_index(op.f('ix_transactions_wells_fargo_has_errors'), table_name='transactions_wells_fargo')
    op.drop_index(op.f('ix_transactions_wells_fargo_cusip'), table_name='transactions_wells_fargo')
    op.drop_index(op.f('ix_transactions_wells_fargo_account_number'), table_name='transactions_wells_fargo')
    op.drop_index(op.f('ix_transactions_wells_fargo_account_name'), table_name='transactions_wells_fargo')
    op.drop_table('transactions_wells_fargo')
    op.drop_index(op.f('ix_transactions_kubera_variance_flag'), table_name='transactions_kubera')
    op.drop_index(op.f('ix_transactions_kubera_transaction_type'), table_name='transactions_kubera')
    op.drop_index(op.f('ix_transactions_kubera_transaction_id'), table_name='transactions_kubera')
    op.drop_index(op.f('ix_transactions_kubera_transaction_date'), table_name='transactions_kubera')
    op.drop_index(op.f('ix_transactions_kubera_symbol'), table_name='transactions_kubera')
    op.drop_index(op.f('ix_transactions_kubera_sheet_name'), table_name='transactions_kubera')
    op.drop_index(op.f('ix_transactions_kubera_settlement_date'), table_name='transactions_kubera')
    op.drop_index(op.f('ix_transactions_kubera_section_name'), table_name='transactions_kubera')
    op.drop_index(op.f('ix_transactions_kubera_matched_to_institution'), table_name='transactions_kubera')
    op.drop_index(op.f('ix_transactions_kubera_kubera_asset_id'), table_name='transactions_kubera')
    op.drop_index(op.f('ix_transactions_kubera_isin'), table_name='transactions_kubera')
    op.drop_index(op.f('ix_transactions_kubera_is_validation_source'), table_name='transactions_kubera')
    op.drop_index(op.f('ix_transactions_kubera_is_processed'), table_name='transactions_kubera')
    op.drop_index(op.f('ix_transactions_kubera_import_batch_id'), table_name='transactions_kubera')
    op.drop_index(op.f('ix_transactions_kubera_has_errors'), table_name='transactions_kubera')
    op.drop_index(op.f('ix_transactions_kubera_cusip'), table_name='transactions_kubera')
    op.drop_index(op.f('ix_transactions_kubera_account_number'), table_name='transactions_kubera')
    op.drop_index(op.f('ix_transactions_kubera_account_name'), table_name='transactions_kubera')
    op.drop_table('transactions_kubera')
    op.drop_index(op.f('ix_transactions_interactive_brokers_transaction_type'), table_name='transactions_interactive_brokers')
    op.drop_index(op.f('ix_transactions_interactive_brokers_transaction_id'), table_name='transactions_interactive_brokers')
    op.drop_index(op.f('ix_transactions_interactive_brokers_transaction_date'), table_name='transactions_interactive_brokers')
    op.drop_index(op.f('ix_transactions_interactive_brokers_symbol'), table_name='transactions_interactive_brokers')
    op.drop_index(op.f('ix_transactions_interactive_brokers_settlement_date'), table_name='transactions_interactive_brokers')
    op.drop_index(op.f('ix_transactions_interactive_brokers_isin'), table_name='transactions_interactive_brokers')
    op.drop_index(op.f('ix_transactions_interactive_brokers_is_processed'), table_name='transactions_interactive_brokers')
    op.drop_index(op.f('ix_transactions_interactive_brokers_import_batch_id'), table_name='transactions_interactive_brokers')
    op.drop_index(op.f('ix_transactions_interactive_brokers_has_errors'), table_name='transactions_interactive_brokers')
    op.drop_index(op.f('ix_transactions_interactive_brokers_cusip'), table_name='transactions_interactive_brokers')
    op.drop_index(op.f('ix_transactions_interactive_brokers_account_number'), table_name='transactions_interactive_brokers')
    op.drop_index(op.f('ix_transactions_interactive_brokers_account_name'), table_name='transactions_interactive_brokers')
    op.drop_table('transactions_interactive_brokers')
    op.drop_index(op.f('ix_transactions_altoira_transaction_type'), table_name='transactions_altoira')
    op.drop_index(op.f('ix_transactions_altoira_transaction_id'), table_name='transactions_altoira')
    op.drop_index(op.f('ix_transactions_altoira_transaction_date'), table_name='transactions_altoira')
    op.drop_index(op.f('ix_transactions_altoira_symbol'), table_name='transactions_altoira')
    op.drop_index(op.f('ix_transactions_altoira_settlement_date'), table_name='transactions_altoira')
    op.drop_index(op.f('ix_transactions_altoira_requires_manual_review'), table_name='transactions_altoira')
    op.drop_index(op.f('ix_transactions_altoira_manually_reviewed'), table_name='transactions_altoira')
    op.drop_index(op.f('ix_transactions_altoira_isin'), table_name='transactions_altoira')
    op.drop_index(op.f('ix_transactions_altoira_is_processed'), table_name='transactions_altoira')
    op.drop_index(op.f('ix_transactions_altoira_import_batch_id'), table_name='transactions_altoira')
    op.drop_index(op.f('ix_transactions_altoira_has_errors'), table_name='transactions_altoira')
    op.drop_index(op.f('ix_transactions_altoira_cusip'), table_name='transactions_altoira')
    op.drop_index(op.f('ix_transactions_altoira_account_number'), table_name='transactions_altoira')
    op.drop_index(op.f('ix_transactions_altoira_account_name'), table_name='transactions_altoira')
    op.drop_table('transactions_altoira')
    op.drop_index(op.f('ix_securities_master_wkn'), table_name='securities_master')
    op.drop_index(op.f('ix_securities_master_type_of_security_level1'), table_name='securities_master')
    op.drop_index(op.f('ix_securities_master_symbol'), table_name='securities_master')
    op.drop_index(op.f('ix_securities_master_sector'), table_name='securities_master')
    op.drop_index(op.f('ix_securities_master_name'), table_name='securities_master')
    op.drop_index(op.f('ix_securities_master_isin'), table_name='securities_master')
    op.drop_table('securities_master')
    op.drop_table('pp_transaction_units')
    op.drop_table('pp_settings')
    op.drop_index(op.f('ix_pp_import_batches_status'), table_name='pp_import_batches')
    op.drop_table('pp_import_batches')
    op.drop_table('pp_client_config')
    op.drop_table('pp_bookmarks')
    op.drop_table('pp_accounts')
    op.drop_index(op.f('ix_kubera_sheets_sheet_name'), table_name='kubera_sheets')
    op.drop_index(op.f('ix_kubera_sheets_pp_group_name'), table_name='kubera_sheets')
    op.drop_table('kubera_sheets')
    op.drop_index(op.f('ix_import_batches_status'), table_name='import_batches')
    op.drop_index(op.f('ix_import_batches_institution'), table_name='import_batches')
    op.drop_table('import_batches')
    op.drop_index(op.f('ix_holding_comparisons_variance_threshold_exceeded'), table_name='holding_comparisons')
    op.drop_index(op.f('ix_holding_comparisons_ticker'), table_name='holding_comparisons')
    op.drop_index(op.f('ix_holding_comparisons_pp_group'), table_name='holding_comparisons')
    op.drop_index(op.f('ix_holding_comparisons_pp_account'), table_name='holding_comparisons')
    op.drop_index(op.f('ix_holding_comparisons_isin'), table_name='holding_comparisons')
    op.drop_index(op.f('ix_holding_comparisons_is_pp_only'), table_name='holding_comparisons')
    op.drop_index(op.f('ix_holding_comparisons_is_matched'), table_name='holding_comparisons')
    op.drop_index(op.f('ix_holding_comparisons_is_kubera_only'), table_name='holding_comparisons')
    op.drop_index(op.f('ix_holding_comparisons_comparison_date'), table_name='holding_comparisons')
    op.drop_table('holding_comparisons')
    # ### end Alembic commands ###
