"""entity registry tables (Phase E1)

Revision ID: d90f75a3b03e
Revises: b8828ce648a2
Create Date: 2026-06-21 10:31:51.009872

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd90f75a3b03e'  # pragma: allowlist secret -- Alembic revision id, not a secret
down_revision: str | None = 'b8828ce648a2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema changes for this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tax_jurisdiction', sa.String(length=50), nullable=True),
    sa.Column('accounting_method', sa.String(length=20), nullable=True),
    sa.Column('direct_investments_only', sa.Boolean(), nullable=False),
    sa.Column('xero_crypto_client_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=True)
    op.create_index(op.f('ix_clients_xero_crypto_client_id'), 'clients', ['xero_crypto_client_id'], unique=True)
    op.create_table('legal_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('tax_form', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('xero_organisation_id', sa.String(length=50), nullable=True),
    sa.Column('pp_portfolio_ref', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'name', name='uq_legal_entity_client_name')
    )
    op.create_index(op.f('ix_legal_entities_client_id'), 'legal_entities', ['client_id'], unique=False)
    op.create_index(op.f('ix_legal_entities_xero_organisation_id'), 'legal_entities', ['xero_organisation_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the schema changes for this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_legal_entities_xero_organisation_id'), table_name='legal_entities')
    op.drop_index(op.f('ix_legal_entities_client_id'), table_name='legal_entities')
    op.drop_table('legal_entities')
    op.drop_index(op.f('ix_clients_xero_crypto_client_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
